version: '3.8'
 
services:
  postgres:
    image: postgres:latest
    container_name: furia
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: furiafuriosa
      POSTGRES_DB: furia_r6
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
 
volumes:
  db_data:
 